/**
 * Employee work-file storage (PDF/Excel attachments).
 *
 * Files live in a single, predictable folder the user can open from the UI:
 *   <Documents>/HR-System/EmployeeFiles
 * The database stores only a unique file name + metadata, so the folder can be
 * browsed/backed up independently of the app database.
 */
import { app, shell } from 'electron'
import fs from 'fs'
import path from 'path'
import { PrismaClient } from '@prisma/client'
import { ApiError } from '../../shared/types'
import type { EmployeeFilePreview } from '../../shared/types'

const ALLOWED_EXTENSIONS = new Set(['.pdf', '.xlsx', '.xls', '.xlsm', '.csv'])
const MAX_FILE_SIZE = 25 * 1024 * 1024 // 25 MB
const PREVIEW_MAX_ROWS = 2000
const PREVIEW_MAX_COLS = 60

export function getEmployeeFilesDir(): string {
  return path.join(app.getPath('documents'), 'HR-System', 'EmployeeFiles')
}

function ensureDir(): string {
  const dir = getEmployeeFilesDir()
  fs.mkdirSync(dir, { recursive: true })
  return dir
}

function sanitizeBaseName(originalName: string): string {
  const ext = path.extname(originalName).toLowerCase()
  const base =
    path
      .basename(originalName, path.extname(originalName))
      .replace(/[\\/:*?"<>|]+/g, '_')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 80) || 'file'
  return `${base}${ext}`
}

function assertAllowedExtension(originalName: string): string {
  const ext = path.extname(originalName).toLowerCase()
  if (!ALLOWED_EXTENSIONS.has(ext)) {
    throw new ApiError('VALIDATION', 'Only PDF and Excel (xlsx/xls/csv) files are allowed')
  }
  return ext
}

function resolveStoredPath(storedName: string): string {
  // storedName is generated by this module, but never trust DB contents in a path.
  const safe = path.basename(storedName)
  if (!safe || safe !== storedName) {
    throw new ApiError('VALIDATION', 'Invalid file name')
  }
  return path.join(getEmployeeFilesDir(), safe)
}

function deleteQuietly(filePath: string): void {
  try {
    fs.rmSync(filePath, { force: true })
  } catch {
    // best effort — a missing/locked file must not break the unlink
  }
}

export interface EmployeeWithFile {
  id: string
  code: string
  fileStoredName: string | null
  fileOriginalName: string | null
}

/** Writes the upload into the files folder and links it to the employee. */
export async function attachEmployeeFile(
  prisma: PrismaClient,
  employeeId: string,
  data: Buffer,
  originalName: string
): Promise<void> {
  assertAllowedExtension(originalName) // validates the extension (stored name keeps it lowercased)
  if (data.byteLength === 0) throw new ApiError('VALIDATION', 'The file is empty')
  if (data.byteLength > MAX_FILE_SIZE) {
    throw new ApiError('VALIDATION', 'File exceeds the 25 MB limit')
  }

  const employee = await prisma.employee.findUnique({ where: { id: employeeId } })
  if (!employee) throw new ApiError('NOT_FOUND', 'Employee not found')

  const dir = ensureDir()
  const storedName = `${String(employee.code).replace(/[^\w-]/g, '_')}_${Date.now()}_${sanitizeBaseName(originalName)}`
  const target = path.join(dir, storedName)
  fs.writeFileSync(target, data)

  // replace: drop the previous physical file, then relink the record
  if (employee.fileStoredName) deleteQuietly(resolveStoredPath(employee.fileStoredName))

  await prisma.employee.update({
    where: { id: employeeId },
    data: {
      fileStoredName: storedName,
      fileOriginalName: originalName,
      fileSize: data.byteLength,
      fileLinkedAt: new Date()
    }
  })
}

/** Unlinks the employee's file and removes it from disk. */
export async function removeEmployeeFile(
  prisma: PrismaClient,
  employeeId: string
): Promise<void> {
  const employee = await prisma.employee.findUnique({ where: { id: employeeId } })
  if (!employee) throw new ApiError('NOT_FOUND', 'Employee not found')
  if (!employee.fileStoredName) throw new ApiError('NOT_FOUND', 'No file is linked')

  deleteQuietly(resolveStoredPath(employee.fileStoredName))

  await prisma.employee.update({
    where: { id: employeeId },
    data: {
      fileStoredName: null,
      fileOriginalName: null,
      fileSize: null,
      fileLinkedAt: null
    }
  })
}

/** Reads the linked file and builds a preview payload (PDF bytes or a grid). */
export async function previewEmployeeFile(
  prisma: PrismaClient,
  employeeId: string
): Promise<EmployeeFilePreview> {
  const employee = await prisma.employee.findUnique({ where: { id: employeeId } })
  if (!employee) throw new ApiError('NOT_FOUND', 'Employee not found')
  if (!employee.fileStoredName) throw new ApiError('NOT_FOUND', 'No file is linked')

  const filePath = resolveStoredPath(employee.fileStoredName)
  if (!fs.existsSync(filePath)) {
    throw new ApiError('NOT_FOUND', 'The file is missing on disk')
  }

  const ext = path.extname(filePath).toLowerCase()
  const size = fs.statSync(filePath).size
  const base = {
    originalName: employee.fileOriginalName,
    ext,
    size
  }

  if (ext === '.pdf') {
    const data = fs.readFileSync(filePath)
    return { kind: 'pdf', ...base, data: new Uint8Array(data) }
  }

  const XLSX = await import('xlsx')
  const workbook = XLSX.read(fs.readFileSync(filePath), { type: 'buffer' })
  const sheetName = workbook.SheetNames[0] ?? null
  const sheet = sheetName ? workbook.Sheets[sheetName] : undefined
  if (!sheet) throw new ApiError('VALIDATION', 'The spreadsheet has no sheets')

  const grid = XLSX.utils.sheet_to_json<string[]>(sheet, {
    header: 1,
    raw: false,
    defval: '',
    blankrows: false
  })
  const totalRows = grid.length
  const rows = grid
    .slice(0, PREVIEW_MAX_ROWS)
    .map((row) => row.slice(0, PREVIEW_MAX_COLS).map((cell) => String(cell ?? '')))

  return {
    kind: 'table',
    ...base,
    sheetName,
    rows,
    totalRows,
    truncated: totalRows > PREVIEW_MAX_ROWS
  }
}

/** Creates the folder if needed and reveals it in the OS file browser. */
export async function revealEmployeeFilesDir(): Promise<void> {
  const dir = ensureDir()
  await shell.openPath(dir)
}
